name: Check for Bonuses
on:
  workflow_dispatch:
  schedule:
    - cron: "0 0 7,14,21,28 * *"

jobs:
  update-bonuses:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          # This is important for pushing back to the repo
          token: ${{ secrets.GITHUB_TOKEN }}
          
      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: "3.12"
          
      - name: Set up environment
        run: |
          python -m pip install --upgrade pip build
          python -m pip install pandas beautifulsoup4 requests
          
      - name: Get bonuses
        env:
          URL: ${{ secrets.BONUS_URL }}
        run: |
          python check.py --url $URL
          
      - name: Commit and push changes
        run: |
          # Configure git
          git config --local user.email "action@github.com"
          git config --local user.name "GitHub Action"
          
          # Add all changes
          git add .
          
          # Check if there are any changes to commit
          if git diff --staged --quiet; then
            echo "No changes to commit"
            exit 0
          fi
          
          # Commit and push
          git commit -m "Update bonuses with new data - $(date +'%Y-%m-%d %H:%M:%S')"
          git push origin main
