name: Check for Bonuses
on:
  workflow_dispatch:
  schedule:
    - cron: "0 0 7,14,21,28 * *"

jobs:
  update-bonuses:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          # This is important for pushing back to the repo
          token: ${{ secrets.GITHUB_TOKEN }}
          persist-credentials: false  # allows custom token usage for push
          fetch-depth: 0  # necessary for pushing changes

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: "3.12"

      - name: Set up environment
        run: |
          python -m pip install --upgrade pip build
          python -m pip install pandas beautifulsoup4 requests

      - name: Get bonuses
        env:
          URL: ${{ secrets.BONUS_URL }}
        run: |
          python check.py --url $URL

      - name: Configure Git for push
        run: |
          git config --global user.name "github-actions[bot]"
          git config --global user.email "41898282+github-actions[bot]@users.noreply.github.com"

      - name: Commit updated bonuses
        run: |
          git add .
          git commit -m "Update bonuses automatically" || echo "No changes to commit"

      - name: Push changes to main
        run: git push origin main
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
